name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      user_defined_tag:
        description: 'Custom tag for the Docker image'
        required: true
      tagAsLatest:
        description: 'Tag as latest ?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build_docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Tag
        id: get_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          fi

      # IF WORKFLOW DISPATCH, W/ TAGASLATEST FALSE BUILD W/ CUSTOM TAG FROM WF DISPATCH
      - name: Build and push only custom tag
        if: ${{ github.event.inputs.tagAsLatest == 'false' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qbittorrent_scheduler:${{ github.event.inputs.user_defined_tag }}

      - name: Build and push latest+custom tag
        if: ${{ github.event.inputs.tagAsLatest == 'true' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qbittorrent_scheduler:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/qbittorrent_scheduler:latest
